import { Column, Entity, PrimaryColumn } from "typeorm";
import { Category } from "./types";

/**
 * Represents a Tag entity in the system. 
 * This entity is used to store and manage information about tags that can be associated with various resources.
 */
@Entity()
export class Tag {

    /**
     * Unique ID of a Tag. 
     * This is a numeric value that is automatically generated by the database when a new Tag is created. 
     * It serves as the primary key for the Tag entity and is used to uniquely identify each Tag in the system.
     * 
     * E.g. 1, 2, 3, 4, 5
     */
    @PrimaryColumn({ type: 'int' })
    tag_id!: number;

    /**
     * The category of the Tag, indicating the type or classification of the tag within the system.
     * This is an enumerated value that can be one of the predefined categories as defined in the Category enum.
     * 
     * E.g. 'food_service_type', 'food_type', 'nutrition_program', etc.
     */
    @Column({ type: 'enum', enum: Category })
    category!: Category;

    /**
     * The label of the Tag, representing the human-readable name or description of the tag.
     * This is a string value that provides a meaningful representation of the tag for display purposes.
     * 
     * E.g. 'Grocery Store', 'Soup Kitchen', 'Food Pantry', etc.
     */
    @Column({ type: 'varchar', length: 255 })
    label!: string;

    /**
     * The slug of the Tag, representing a URL-friendly version of the tag label.
     * This is a string value that is makes it easier to use the tag.
     * 
     * E.g. 'grocery-store', 'soup-kitchen', 'food-pantry', etc.
     */
    @Column({ type: 'varchar', length: 255 })
    slug!: string;

}