import { Entity, Column, PrimaryColumn } from 'typeorm';

import { Type } from './types';

/**
 * Represents a Staff user in the system. This entity is used to store and manage information about staff members.
 * 
 * This Includes Community Staff (Community Health Workers, Community Engagement Workers) and Admin Staff.
 */
@Entity()
export class Staff {
  /**
   * Unique ID of a Staff User. 
   * This is a numeric value that is automatically generated by the database when a new Staff user is created. 
   * It serves as the primary key for the Staff entity and is used to uniquely identify each Staff user in the system.
   * 
   * E.g. 1, 2, 3, 4, 5
   */
  @PrimaryColumn({ type: 'int'})
  id: number;

  /**
   * The type of the Staff user, indicating their role or level of access within the system.
   * This is an enumerated value that can be either 'ADMIN' or 'STANDARD', as defined in the type enum.
   * 
   * E.g. 'ADMIN', 'STANDARD'
   */
  @Column({ type: 'enum', enum: Type })
  type: Type;

  /**
   * The first name of the Staff user. This is a string value that represents the given name of the Staff user.
   * 
   * E.g. 'John', 'Jane'
   */
  @Column({ type: 'varchar', length: 255 })
  firstName: string;

  /**
   * The last name of the Staff user. This is a string value that represents the family name or surname of the Staff user.
   * 
   * E.g. 'Doe', 'Smith'
   */
  @Column({ type: 'varchar', length: 255 })
  lastName: string;

  /**
   * The email address of the Staff user. This is a string value that represents the email contact information for the Staff user.
   * It is used for communication and authentication purposes within the system.
   * 
   * E.g. 'john.doe@example.com', 'jane.smith@example.com'
   */
  @Column({ type: 'varchar', length: 255 })
  email: string;
}
