import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';
import { Category, County } from './types';

/**
 * Represents a Resource entity.
 *
 * This entity is used to store data sources like food pantries or housing programs.
 */
@Entity()
export class Resource {
  /**
   * Unique ID of a Resource.
   * This is a numeric value that is automatically generated by the database when a new Resource is created.
   * It serves as the primary key for the Resource entity and is used to uniquely identify each Resource in the system.
   *
   * E.g. 1, 2, 3, 4, 5
   */
  @PrimaryGeneratedColumn({ type: 'int' })
  resource_id!: number;

  /**
   * ID of the Score associated with this Resource.
   * This will reference the Score entity once that relationship is established.
   *
   * E.g. 1, 2, 3
   */
  @Column({ type: 'int' })
  score_id!: number;

  /**
   * The name of the Resource, representing the title used to identify it.
   * This is a string value that provides a meaningful representation of the resource for display purposes.
   *
   * E.g. 'Greater Boston Food Bank', 'Pine Street Inn'
   */
  @Column({ type: 'varchar', length: 255 })
  name!: string;

  /**
   * The category (or categories) the Resource belongs to.
   * This is stored as an array since a single Resource may span more than one Category.
   *
   * E.g. [Category.FOOD_ACCESS], [Category.HOUSING, Category.OTHER]
   */
  @Column({ type: 'enum', enum: Category, array: true })
  category!: Category[];

  /**
   * A free-text description of the Resource providing further detail beyond its name.
   * This is a string value that gives additional context about what the resource offers.
   *
   * E.g. 'Provides free groceries and hot meals to families in the Greater Boston area.'
   */
  @Column({ type: 'text', nullable: true })
  description?: string;

  /**
   * The street address of the Resource's location.
   * This is a string value used to help people locate the resource in person.
   *
   * E.g. '123 Main St, Boston, MA 02115'
   */
  @Column({ type: 'varchar', length: 255, nullable: true })
  address?: string;

  /**
   * The Massachusetts county the Resource is located in.
   * This is an enumerated value that can be utilized by the filter.
   *
   * E.g. County.SUFFOLK, County.MIDDLESEX
   */
  @Column({ type: 'enum', enum: County })
  county!: County;

  /**
   * The ZIP code of the Resource's location.
   * This is a string value that can be utilized by the filter.
   *
   * E.g. '02115', '01960'
   */
  @Column({ type: 'varchar', length: 10 })
  zip_code!: string;

  /**
   * The contact phone number for the Resource.
   * This is a string value, left optional since some resources may only be reachable by website or email.
   *
   * E.g. '(617) 555-0100'
   */
  @Column({ type: 'varchar', length: 20, nullable: true })
  phone?: string;

  /**
   * The contact email address for the Resource.
   * This is a string value, left optional since some resources may only be reachable by phone or website.
   *
   * E.g. 'contact@example.org'
   */
  @Column({ type: 'varchar', length: 255, nullable: true })
  email?: string;

  /**
   * The website URL for the Resource.
   * This is a string value, left optional since not every organization has one.
   *
   * E.g. 'https://www.example.org'
   */
  @Column({ type: 'varchar', length: 255, nullable: true })
  website?: string;

  /**
   * A written description of who is eligible to use the Resource.
   * This is a string value that details any restrictions or requirements for access.
   *
   * E.g. 'Open to all Massachusetts residents; no ID required.'
   */
  @Column({ type: 'text', nullable: true })
  eligibility?: string;

  /**
   * The date the Resource's information was last verified.
   * This is set when the Resource is created and is expected to be updated as it's re-verified over time.
   *
   * E.g. new Date('2026-01-15')
   */
  @Column({ type: 'date' })
  last_verified_date!: Date;

  /**
   * The vetting status of the Resource, indicating how much its information has been verified.
   * This is stored as plain text for now since the verification/scoring process hasn't been finalized.
   *
   * E.g. 'verified', 'pending review'
   */
  @Column({ type: 'varchar', length: 255 })
  vetting_status!: string;

  /**
   * Internal notes left by a reviewer while vetting the Resource.
   * This is a string value intended for internal use only and won't exist for every resource.
   *
   * E.g. 'Called and confirmed hours; still need to verify eligibility requirements.'
   */
  @Column({ type: 'text', nullable: true })
  reviewer_notes?: string;

  /**
   * The list of Tag IDs associated with this Resource.
   * This starts as an empty array when a Resource is created and can have Tag IDs added to it over time.
   *
   * E.g. [], [1, 4, 7]
   */
  @Column({ type: 'int', array: true, default: '{}' })
  tags!: number[];
}
