import { Entity, PrimaryColumn } from 'typeorm';

/**
 * Represents a Score entity in the system.
 * This entity is used to store and manage information about scores associated with various resources.
 */
@Entity()
export class Score {
  /**
   * Unique ID of a Score.
   * This is a numeric value that is automatically generated by the database when a new Score is created.
   * It serves as the primary key for the Score entity and is used to uniquely identify each Score in the system.
   *
   * E.g. 1, 2, 3, 4, 5
   */
  @PrimaryColumn({ type: 'int' })
  score_id!: number;
}
