name: Backend build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use NodeJS 24.x
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'yarn'


    - name: Create .env file
      run: |
        echo "POSTGRES_HOST=localhost" >> .env
        echo "POSTGRES_PORT=5432" >> .env
        echo "POSTGRES_USER=fenway_health_user" >> .env
        echo "POSTGRES_PASSWORD=12345678" >> .env
        echo "POSTGRES_DB=proj_fh" >> .env

    - name: Install Dependencies
      run: yarn install

    - name: Build backend
      run: npx nx build backend
