name: Jest run

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:24-alpine

    steps:
    - uses: actions/checkout@v4

    - name: Enable Corepack (helps to pin yarn version)
      run: corepack enable

    - name: Create .env file
      run: |
        echo "POSTGRES_HOST=localhost" >> .env
        echo "POSTGRES_PORT=5432" >> .env
        echo "POSTGRES_USER=fenway_health_user" >> .env
        echo "POSTGRES_PASSWORD=12345678" >> .env
        echo "POSTGRES_DB=proj_fh" >> .env

    - name: Install Dependencies
      run: yarn install

    - name: Run Jest tests 
      run: yarn test
